name: Deploy Private GitHub repository to cPanel
on:
  push:
    branches:
      - main
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: ⚙️ Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: 📦 Install dependencies
        run: npm ci
      - name: 🏗️ Build static export
        run: npm run build
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          dangerous-clean-slate: true
